jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install Pandoc
        run: |
          sudo apt-get update
          sudo apt-get -y install pandoc
      
      - name: Convert Markdown to HTML
        run: |
          find . -type f -name "*.md" -print0 | while read -d $'\0' file
          do
            pandoc "$file" -s -o "${file%.md}.html"
          done

  pages:
    stage: deploy
    script:
    - mkdir .public
    - cp -r * .public
    - mv .public public
    artifacts:
      paths:
      - public
    only:
    - main
