buile:
  stage: build
  script:    
    - node -v

test:
  stage: test
  script:
    - echo "This job tests something"

pages:
  stage: deploy
  script:
  - mkdir .public
  - cp -r * .public
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - main
