name: skt_workflow
jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - name: Generate HTMLs from Markdown
        run: |
          find . -type f -name "*.md" -print0 | while read -d $'\0' file
          do
            pandoc --output="${file%}.html" "$file"
          done
          curr_dir=$(pwd)
          echo "<h1>${curr_dir##*/}</h1><br/>">>index.html
          find . -type f -name "*.md.html" -print0 | while read -d $'\0' file
          do
            curr_dir=${curr_dir##*/}
            file_name=${file#*.}
            echo "<img src='https://img.icons8.com/color/28/null/copy--v1.png' onClick=\"navigator.clipboard.writeText(window.location.hostname+'/${curr_dir}+${file_name}');\"/>">>index.html      
            echo "<a href=\"${file}\" target=\"blank\">${file_name}</a><br/>">>index.html
          done
          mkdir .public
          cp -r * .public
          mv .public public
on:
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]
